Update README.md, NPM not supported info.
dolbyio-samples/media-app-react-music-mastering pull request #6
Opened 2022-08-19 00:35 UTC by chriswrightDIO

Signed-off-by: chriswrightDIO <111305245+chriswrightDIO@users.noreply.github.com>

2022-08-19 00:38 UTC, chriswrightDIO commented
Hi Thomas, can you please approve the readme update? Thanks.

2022-08-23 19:06 UTC, FabienLavocat requested changes

2022-08-23 19:06 UTC, FabienLavocat commented on README.md
> +
Can you remove those extra lines

2022-08-23 19:16 UTC, chriswrightDIO commented on README.md
> +
Fixed.

2022-08-23 21:41 UTC, FabienLavocat approved these changes

2022-08-23 21:42 UTC, merged